//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToTicketsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Main = new HashSet<Main>();
        }
    
        public int ppers_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_begin_ed { get; set; }
        public Nullable<System.DateTime> date_end_ed { get; set; }
    
        public virtual ICollection<Main> Main { get; set; }
    }
}
