//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToTicketsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Main = new HashSet<Main>();
        }
    
        public int tticket_id { get; set; }
        public string ticket_name { get; set; }
        public int tprice_id { get; set; }
        public int trate_id { get; set; }
        public int ttype_id { get; set; }
    
        public virtual ICollection<Main> Main { get; set; }
        public virtual Price Price { get; set; }
        public virtual Rate Rate { get; set; }
        public virtual Type Type { get; set; }
    }
}
