//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToTicketsDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tr_Tick_DBEntities : DbContext
    {
        public Tr_Tick_DBEntities()
            : base("name=Tr_Tick_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Main> Main { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<Price> Price { get; set; }
        public DbSet<Rate> Rate { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<Type> Type { get; set; }
    }
}
