//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToTicketsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int ttype_id { get; set; }
        public string ttype_name { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
